### ISSUE TITLE
网盘站点更新修复木偶添加小米UC网盘

### ISSUE THREAD

**Issue by Simiandeye** [YYDS678/uzVideo-extensions#10]
{
    "name": "🐱玩偶备用",
    "api": "https://8704.kstore.space/Shimiandeye/uz/vod/js/wobg.js",
    "instance": "wobg20241127",
    "webSite": "http://wogg.xxooo.cf",
    "remark": "网盘",
    "version": "2",
    "type": 100
  },
  {
    "name": "🪵木偶哥哥",
    "api": "https://8704.kstore.space/Shimiandeye/uz/vod/js/mogg.js",
    "instance": "smdymogg20241127",
    "webSite": "http://www.muoupan.top",
    "remark": "网盘",
    "version": "2",
    "type": 100
  },
  {
    "name": "🌾小米网盘",
    "api": "https://8704.kstore.space/Shimiandeye/uz/vod/js/xiaomi.js",
    "instance": "smdyxiaomi20241127",
    "webSite": "http://www.mucpan.cc",
    "remark": "网盘",
    "version": "2",
    "type": 100
  },
  {
    "name": "⚡️至臻网盘",
    "api": "https://8704.kstore.space/Shimiandeye/uz/vod/js/zhizhen.js",
    "instance": "smdyzhizhen20241127",
    "webSite": "https://mihdr.top",
    "remark": "网盘",
    "version": "2",
    "type": 100
  },
  {
    "name": "🖍蜡笔小新",
    "api": "https://8704.kstore.space/Shimiandeye/uz/vod/js/labipan.js",
    "instance": "labipan20241127",
    "webSite": "https://duopan.fun",
    "remark": "网盘",
    "version": "2",
    "type": 100
  },
  {
    "name": "🤠多多影音",
    "api": "https://8704.kstore.space/Shimiandeye/uz/vod/js/duoduo.js",
    "instance": "smdyduoduo20241127",
    "webSite": "https://tv.yydsys.top",
    "remark": "网盘",
    "version": "2",
    "type": 100
  },
  {
    "name": "🐲欧歌资源",
    "api": "https://8704.kstore.space/Shimiandeye/uz/vod/js/ouge.js",
    "instance": "smdyouge20241127",
    "webSite": "https://woog.nxog.eu.org",
    "remark": "网盘",
    "version": "2",
    "type": 100
  },
  {
    "name": "🤙🏻六趣网盘",
    "api": "https://8704.kstore.space/Shimiandeye/uz/vod/js/liuqu.js",
    "instance": "smdyliuqu20241127",
    "webSite": "https://wp.0v.fit",
    "remark": "网盘",
    "version": "2",
    "type": 100
  },
 {
    "name": "💧哔嘀影视",
    "api": "https://8704.kstore.space/Shimiandeye/uz/vod/js/biliys.js",
    "instance": "yjys20240824",
    "webSite": "https://www.xlys01.com",
    "remark": "",
    "version": "2",
    "type": 100
  }
[smdy.zip](https://github.com/user-attachments/files/17955252/smdy.zip)
祝uz影视越来越好

**Comment by YYDS678** [comment]
❤️感谢！已整合
