### ISSUE TITLE
uz影视网盘扩展

### ISSUE THREAD

**Issue by Simiandeye** [YYDS678/uzVideo-extensions#2]
[🔧uz影视扩展.zip](https://github.com/user-attachments/files/17570115/uz.zip)
{
        "name": "⚡️至臻网盘",
        "api": "https://gitee.com/xiaoyu4k/uz/raw/smdy/js/zhizhen.js",
        "instance": "zhizhen20241029",
        "webSite": "https://mihdr.top/",
        "remark": "至臻网盘"
    },
    {
        "name": "🤠多多影音",
        "api": "https://gitee.com/xiaoyu4k/uz/raw/smdy/js/duopan.js",
        "instance": "duopan20241030",
        "webSite": "https://tv.yydsys.top/",
        "remark": "多多网盘"
    },
    {
        "name": "🐲欧歌资源",
        "api": "https://gitee.com/xiaoyu4k/uz/raw/smdy/js/ougepan.js",
        "instance": "ougepan20241030",
        "webSite": "https://woog.nxog.eu.org/",
        "remark": "欧歌网盘"
    },
    {
        "name": "🍔奥秘影视",
        "api": "https://gitee.com/xiaoyu4k/uz/raw/smdy/js/aomipan.js",
        "instance": "aomipan20241030",
        "webSite": "https://vip.omii.top/",
        "remark": "奥秘网盘"
    },
    {
        "name": "⛅️云星日记",
        "api": "https://gitee.com/xiaoyu4k/uz/raw/smdy/js/yunxing.js",
        "instance": "yunxing20241030",
        "webSite": "https://4k.4u4.cn",
        "remark": "云星网盘"
    },
    {
        "name": "🥔土豆粉条",
        "api": "https://gitee.com/xiaoyu4k/uz/raw/smdy/js/tudou.js",
        "instance": "tudou20241030",
        "webSite": "https://yunpan.yunpay.cc",
        "remark": "土豆网盘"
    }

**Comment by YYDS678** [comment]
已添加 感谢！
