### ISSUE TITLE
扩展代码支持本地吗

### ISSUE THREAD

**Issue by yongheng66** [YYDS678/uzVideo-extensions#7]
请问你这个账号是官方的吗？我看了扩展添加只支持链接，没有文件导入之类的，api也全是http，没有本地的，如何你是官方麻烦加一下本地扩展支持，如果不是，麻烦转告一下，谢谢！习惯了猫影视的本地开发方式，代码放网上总是很多不便。

**Comment by YYDS678** [comment]
可以在 PC 端开启局域网共享服务，配置一下 导入后关了就行。

**Comment by yongheng66** [comment]
不知道你说的啥，那我还是继续用猫影视吧

**Comment by dddfdr** [comment]
.最新版本1.6.37长按快进后 松开不能取消快进 还会出现音画不同步没有声音

**Comment by dddfdr** [comment]
.最新版本1.6.37长按快进后 松开不能取消快进 还会出现音画不同步没有声音
